# Generated by Django 4.2 on 2023-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_testfilefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=40, null=True)),
                ('image', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
                ('min', models.IntegerField()),
                ('MABP', models.FloatField()),
                ('currency', models.CharField(max_length=2)),
                ('storage', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestFileField',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
